export const palabrasOrdenadas = [
  "Camino",
  "Amigos",

  "Ruedas",
  "Nubes",
  "Flores",
  "Correr",
  "Cuerda",
  "Brillo",
  "Gritos",
  "Trajes",
  "Letras",
  "Sillas",
  "Brumas",
  "Saltar",
  "Bailes",
  "Campos",
  "Fuegos",
  "Dibuje",
  "Pistas",
  "Sol",
  "Mar",
  "Luz",
  "Paz",

  "Mesa",
  "Flor",
  "Casa",
  "Luna",
  "Oro",

  "Perro",
  "Silla",
  "Carro",
  "Llave",
  "Gatos",
  "Barco",
  "Raton",
  "Mano",
  "Rueda",
];
export const palabrasDesordenadas = [
  {
    desordenado1: "iamnco",
    desordenado2: "osmiga",

    desordenado4: "sedaru",
    desordenado5: "seunb",
    desordenado6: "oserlf",
    desordenado7: "rcorer",
    desordenado8: "adurec",
    desordenado9: "lborli",
    desordenado10: "igorst",
    desordenado11: "ejtsra",
    desordenado12: "rstael",
    desordenado13: "sallis",
    desordenado14: "sbumar",
    desordenado15: "atlsra",
    desordenado16: "isealb",
    desordenado17: "ospmac",
    desordenado18: "ogseuf",
    desordenado19: "bujeid",
    desordenado20: "tspasi",
    desordenado21: "lso",
    desordenado22: "amr",
    desordenado23: "zlu",
    desordenado24: "zpa",

    desordenado26: "same",
    desordenado27: "lorf",
    desordenado28: "asac",
    desordenado29: "unal",
    desordenado30: "roo",

    desordenado32: "orper",
    desordenado33: "lasil",
    desordenado34: "ocrra",
    desordenado35: "evlla",
    desordenado36: "tsago",
    desordenado37: "oacrb",
    desordenado38: "tnoar",
    desordenado39: "omna",
    desordenado40: "uedar",
  },
];
