export const palabrasOrdenadas = [
  "camino",
  "amigos",
  "ruedas",
  "nubes",
  "flores",
  "correr",
  "cuerda",
  "brillo",
  "gritos",
  "trajes",
  "letras",
  "sillas",
  "brumas",
  "saltar",
  "bailes",
  "campos",
  "fuegos",
  "dibuje",
  "pistas",
  "sol",
  "mar",
  "luz",
  "paz",
  "mesa",
  "flor",
  "casa",
  "luna",
  "perro",
  "silla",
  "carro",
  "llave",
  "gatos",
  "barco",
  "raton",
  "mano",
  "rueda",
];
export const palabrasDesordenadas = [
  {
    desordenado1: "iamnco",
    desordenado2: "osmiga",
    desordenado3: "sedaru",
    desordenado4: "seunb",
    desordenado5: "oserlf",
    desordenado6: "rcorer",
    desordenado7: "adurec",
    desordenado8: "lborli",
    desordenado9: "igorst",
    desordenado10: "ejtsra",
    desordenado11: "rstael",
    desordenado12: "sallis",
    desordenado13: "sbumar",
    desordenado14: "atlsra",
    desordenado15: "isealb",
    desordenado16: "ospmac",
    desordenado17: "ogseuf",
    desordenado18: "bujeid",
    desordenado19: "tspasi",
    desordenado20: "lso",
    desordenado21: "amr",
    desordenado22: "zlu",
    desordenado23: "zpa",
    desordenado24: "same",
    desordenado25: "lorf",
    desordenado26: "asac",
    desordenado27: "unal",
    desordenado28: "roo",
    desordenado29: "orper",
    desordenado30: "lasil",
    desordenado31: "ocrra",
    desordenado32: "evlla",
    desordenado33: "tsago",
    desordenado34: "oacrb",
    desordenado35: "tnoar",
    desordenado36: "omna",
    desordenado37: "uedar",
  },
];
